
# file="/home/brams/.config/i3/themes-rs/nord-dark.toml"
theme = "nord-dark"
icons = "awesome"

[[block]]
block = "focused_window"
max_width = 23
show_marks = "visible"
format="{combo}"

# [[block]]
# block = "speedtest"
# interval = 1800
# format = "{speed_down:4*B}{speed_up:4*B}"

[[block]]
block = "uptime"

[[block]]
block = "disk_space"
path = "/home"
alias = "/"
info_type = "available"
format="{icon} {available}"
unit = "GB"
interval = 600
warning = 20.0
alert = 10.0

# [[block]]
# block = "pomodoro"
# length = 25
# break_length = 5
# message = "Take a break!"
# break_message = "Back to work!"
# notifier = "swaynag"

[[block]]
block = "music"
player = "spotify"
buttons = ["prev", "play", "next"]
max_width=10
dynamic_width=true
# hide_when_empty=true

[[block]]
block = "nvidia_gpu"
label = ""
show_memory = false
show_clocks = false
interval = 1

[[block]]
block = "memory"
format_mem = "{mem_used}({mem_used_percents})"
format_swap = "{swap_used}({swap_used_percents})"
display_type = "memory"
icons = true
clickable = true
interval = 5
warning_mem = 80
warning_swap = 80
critical_mem = 95
critical_swap = 95

[[block]]
block = "cpu"
interval = 1
format = "{utilization}({frequency})"

[[block]]
block = "pacman"
interval = 600
format = "{both}"
format_singular = "{both}"
format_up_to_date = "None"
critical_updates_regex = "(linux|linux-lts|linux-zen)"
# aur_command should output available updates to stdout (ie behave as echo -ne "update\n")
aur_command = "yay -Qua"
on_click = "fakeroot pacman -Qu --dbpath /tmp/checkup-db-brams/ | kitty yay"


[[block]]
block = "sound"
step_width = 5
max_vol=100
format = "{volume}"


[[block]]
block = "time"
format = "%d/%m/%g | %R"
on_click = "%A, %d %B %Y"
timezone = "Europe/Luxembourg"
interval = 1
# locale = "en_GB"

# [[block]]
# block = "battery"
# if_command = "test -e /sys/class/power_supply/BAT0"

